services:
  credentials:
    volumes:
      - ${DEVSTACK_WORKSPACE}/credentials:/edx/app/credentials/credentials
      - credentials_node_modules:/edx/app/credentials/credentials/node_modules
      - credentials_tox:/edx/app/credentials/credentials/.tox
      - ${DEVSTACK_WORKSPACE}/src:/edx/src
      - ${PWD}/py_configuration_files/credentials.py:/edx/app/credentials/credentials/credentials/settings/devstack.py
  discovery:
      volumes:
      - ${DEVSTACK_WORKSPACE}/course-discovery:/edx/app/discovery/discovery
      - discovery_node_modules:/edx/app/discovery/discovery/node_modules
      - discovery_tox:/edx/app/discovery/discovery/.tox
      - ${DEVSTACK_WORKSPACE}/src:/edx/src
      - ${PWD}/py_configuration_files/course_discovery.py:/edx/app/discovery/discovery/course_discovery/settings/devstack.py
  ecommerce:
    volumes:
      - ${DEVSTACK_WORKSPACE}/ecommerce:/edx/app/ecommerce/ecommerce
      - ecommerce_node_modules:/edx/app/ecommerce/ecommerce/node_modules
      - ecommerce_tox:/edx/app/ecommerce/ecommerce/.tox
      - ${DEVSTACK_WORKSPACE}/src:/edx/src
      - ${PWD}/py_configuration_files/ecommerce.py:/edx/app/ecommerce/ecommerce/ecommerce/settings/devstack.py
  forum:
    volumes:
      - ${DEVSTACK_WORKSPACE}/cs_comments_service:/edx/app/forum/cs_comments_service
  lms:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform
      - edxapp_media:/edx/var/edxapp/media
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - edxapp_tox:/edx/app/edxapp/edx-platform/.tox
      - edxapp_uploads:/edx/var/edxapp/uploads
      - ${DEVSTACK_WORKSPACE}/src:/edx/src
      - ${PWD}/py_configuration_files/cms.py:/edx/app/edxapp/edx-platform/cms/envs/devstack.py
      - ${PWD}/py_configuration_files/lms.py:/edx/app/edxapp/edx-platform/lms/envs/devstack.py
  lms-worker:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform
  edx_notes_api:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-notes-api:/edx/app/notes/
      - ${DEVSTACK_WORKSPACE}/src:/edx/src
      - ${PWD}/py_configuration_files/edx_notes_api.py:/edx/app/notes/notesserver/settings/devstack.py
  registrar:
    volumes:
      - ${DEVSTACK_WORKSPACE}/registrar:/edx/app/registrar
      - ${PWD}/py_configuration_files/registrar.py:/edx/app/registrar/registrar/registrar/settings/devstack.py
  registrar-worker:
    volumes:
      - ${DEVSTACK_WORKSPACE}/registrar:/edx/app/registrar
  cms:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform
      - edxapp_media:/edx/var/edxapp/media
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - edxapp_tox:/edx/app/edxapp/edx-platform/.tox
      - edxapp_uploads:/edx/var/edxapp/uploads
      - ${DEVSTACK_WORKSPACE}/src:/edx/src
      - ${PWD}/py_configuration_files/cms.py:/edx/app/edxapp/edx-platform/cms/envs/devstack.py
      - ${PWD}/py_configuration_files/lms.py:/edx/app/edxapp/edx-platform/lms/envs/devstack.py
  cms-worker:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform
  codejail:
    volumes:
      - ${DEVSTACK_WORKSPACE}/codejail-service:/app
      - ${DEVSTACK_WORKSPACE}/src:/edx/src
      - ${PWD}/py_configuration_files/codejail.py:/app/codejail_service/settings/devstack.py
  insights:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-analytics-dashboard:/edx/app/insights/insights
      - insights_node_modules:/edx/app/insights/insights/node_modules
      - ${PWD}/py_configuration_files/analytics_dashboard.py:/edx/app/insights/edx_analytics_dashboard/edx_analytics_dashboard/settings/devstack.py
  analyticsapi:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-analytics-data-api:/edx/app/analytics_api/analytics_api
      - ${DEVSTACK_WORKSPACE}/src:/edx/src
      - ${PWD}/py_configuration_files/analytics_data_api.py:/edx/app/analytics_api/analytics_api/analyticsdataserver/settings/devstack.py
  enterprise-catalog:
    volumes:
      - ${DEVSTACK_WORKSPACE}/enterprise-catalog:/edx/app/enterprise_catalog/enterprise_catalog
  enterprise-catalog-worker:
    volumes:
      - ${DEVSTACK_WORKSPACE}/enterprise-catalog:/edx/app/enterprise_catalog/enterprise_catalog
      - ${PWD}/py_configuration_files/enterprise_catalog.py:/edx/app/enterprise_catalog/enterprise_catalog/settings/devstack.py
  enterprise-catalog-curations-worker:
    volumes:
      - ${DEVSTACK_WORKSPACE}/enterprise-catalog:/edx/app/enterprise_catalog/enterprise_catalog
  license-manager:
    volumes:
      - ${DEVSTACK_WORKSPACE}/license-manager:/edx/app/license_manager
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
      - ${PWD}/py_configuration_files/license_manager.py:/edx/app/license_manager/license_manager/settings/devstack.py
  license-manager-worker:
    volumes:
      - ${DEVSTACK_WORKSPACE}/license-manager:/edx/app/license_manager
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
      - ${PWD}/py_configuration_files/license_manager.py:/edx/app/license_manager/license_manager/settings/devstack.py
  bulk-enrollment-worker:
    volumes:
      - ${DEVSTACK_WORKSPACE}/license-manager:/edx/app/license_manager
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
      - ${PWD}/py_configuration_files/license_manager.py:/edx/app/license_manager/license_manager/settings/devstack.py
  # Note that frontends mount `src` to /edx/app/src instead of /edx/src.
  # See ADR #5 for rationale.
  frontend-app-account:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-account:/edx/app/frontend-app-account
      - frontend_app_account_node_modules:/edx/app/frontend-app-account/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src

  frontend-app-profile:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-profile:/edx/app/frontend-app-profile
      - frontend_app_profile_node_modules:/edx/app/frontend-app-profile/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src

  frontend-app-authn:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-authn:/edx/app/frontend-app-authn
      - frontend_app_authn_node_modules:/edx/app/frontend-app-authn/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src

  frontend-app-course-authoring:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-course-authoring:/edx/app/frontend-app-course-authoring
      - frontend_app_course_authoring_node_modules:/edx/app/frontend-app-course-authoring/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src
  frontend-app-gradebook:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-gradebook:/edx/app/frontend-app-gradebook
      - frontend_app_gradebook_node_modules:/edx/app/frontend-app-gradebook/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src
  frontend-app-ora-grading:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-ora-grading:/edx/app/frontend-app-ora-grading
      - frontend_app_ora_grading_node_modules:/edx/app/frontend-app-ora-grading/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src
  frontend-app-learner-dashboard:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-learner-dashboard:/edx/app/frontend-app-learner-dashboard
      - frontend_app_learner_dashboard_node_modules:/edx/app/frontend-app-learner-dashboard/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src
  frontend-app-learner-record:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-learner-record:/edx/app/frontend-app-learner-record
      - frontend_app_learner_record_node_modules:/edx/app/frontend-app-learner-record/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src
  frontend-app-learning:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-learning:/edx/app/frontend-app-learning
      - frontend_app_learning_node_modules:/edx/app/frontend-app-learning/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src
  frontend-app-library-authoring:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-library-authoring:/edx/app/frontend-app-library-authoring
      - frontend_app_library_authoring_node_modules:/edx/app/frontend-app-library-authoring/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src
  frontend-app-payment:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-payment:/edx/app/frontend-app-payment
      - frontend_app_payment_node_modules:/edx/app/frontend-app-payment/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src
  frontend-app-program-console:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-program-console:/edx/app/frontend-app-program-console
      - frontend_app_program_console_node_modules:/edx/app/frontend-app-program-console/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src
  frontend-app-publisher:
    volumes:
      - ${DEVSTACK_WORKSPACE}/frontend-app-publisher:/edx/app/frontend-app-publisher
      - frontend_app_publisher_node_modules:/edx/app/frontend-app-publisher/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src

volumes:
  credentials_node_modules:
  discovery_node_modules:
  ecommerce_node_modules:
  insights_node_modules:
  edxapp_media:
  edxapp_node_modules:
  edxapp_uploads:
  frontend_app_account_node_modules:
  frontend_app_profile_node_modules:
  frontend_app_authn_node_modules:
  frontend_app_course_authoring_node_modules:
  frontend_app_gradebook_node_modules:
  frontend_app_ora_grading_node_modules:
  frontend_app_learner_dashboard_node_modules:
  frontend_app_learner_record_node_modules:
  frontend_app_learning_node_modules:
  frontend_app_library_authoring_node_modules:
  frontend_app_payment_node_modules:
  frontend_app_program_console_node_modules:
  frontend_app_publisher_node_modules:
  credentials_tox:
  discovery_tox:
  ecommerce_tox:
  edxapp_tox:
